/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.Paths;
import java.util.List;
import java.util.stream.Collectors;

public class App {

    public static void main(String[] args) {

        try {
            // Get the path to the file
            String strFilePath = ClassLoader.getSystemResource("file.txt").getPath();
            Path filePath = Paths.get(strFilePath);

            // Read the file and parse it to a list
            List<String> lines = Files.lines(filePath)
                    .collect(Collectors.toList());
            String[] linesArray = lines.toArray(new String[0]);

            // Print the array to verify
            for (String line : linesArray) {
                System.out.println(line);
            }
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
}
